kind: Template
apiVersion: v1
metadata:
  name: turing

parameters:
  - name: INFODIOD_SERVICE
    value: "http://infodiod-service-route.turing.svc:8080"
    required: true
  - name: TURING_DUMP_PVC_MOUNT_PATH
    value: "/mnt/turing/dump/volume"
    required: true
  - name: CURRENT_ZONE
    value: "DEV | TEST"
    required: true


objects:
# ========================== INFODIOD-SERVICE ==========================
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: infodiod-service
      annotations:
        template.alpha.openshift.io/wait-for-ready: "true"
    spec:
      replicas: 1
      selector:
        deploymentconfig: infodiod-service
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            deploymentconfig: infodiod-service
        spec:
          containers:
            - image: "172.30.1.1:5000/turing/infodiod:0.0.2"
              imagePullPolicy: Always
              name: infodiod
              ports:
                - containerPort: 8080
                  protocol: TCP
              volumeMounts:
                - mountPath: "${TURING_DUMP_PVC_MOUNT_PATH}"
                  name: "turing-dump-pv"
              env:
                - name: TURING_DUMP_PVC_MOUNT_PATH
                  value: ${TURING_DUMP_PVC_MOUNT_PATH}
                - name: CURRENT_ZONE
                  value: ${CURRENT_ZONE}
          volumes:
            - name: "turing-dump-pv"
              persistentVolumeClaim:
                claimName: "turing-dump-pvc"
    restartPolicy: Always
  - kind: Service
    apiVersion: v1
    metadata:
      name: infodiod-service-route
    spec:
      ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: infodiod-service
      type: ClusterIP
# ========================== ODUMP-SERVICE ==========================
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: odump-service
      annotations:
        template.alpha.openshift.io/wait-for-ready: "true"
    spec:
      replicas: 1
      selector:
        deploymentconfig: odump-service
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            deploymentconfig: odump-service
        spec:
          containers:
            - image: "172.30.1.1:5000/turing/odump:0.0.3"
              imagePullPolicy: Always
              name: odump
              ports:
                - containerPort: 8080
                  protocol: TCP
              volumeMounts:
                - mountPath: "${TURING_DUMP_PVC_MOUNT_PATH}"
                  name: "turing-dump-pv"
              env:
                - name: CURRENT_ZONE
                  value: ${CURRENT_ZONE}
                - name: INFODIOD_SERVICE
                  value: ${INFODIOD_SERVICE}
                - name: TURING_DUMP_PVC_MOUNT_PATH
                  value: ${TURING_DUMP_PVC_MOUNT_PATH}
          volumes:
            - name: "turing-dump-pv"
              persistentVolumeClaim:
                claimName: "turing-dump-pvc"
    restartPolicy: Always
  - kind: Service
    apiVersion: v1
    metadata:
      name: odump-service-route
    spec:
      ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: odump-service
      type: ClusterIP

  - kind: Route
    apiVersion: v1
    metadata:
      name: odump
      namespace: turing
    spec:
      to:
        kind: Service
        name: odump-service-route
